In [27]:
import torch

import numpy as np

In [28]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
#vector
t1 = [1., 2., 3.]
t1_tensor = torch.tensor(t1)
print('Vector ::',t1)
print('1D tensor ::',t1_tensor)
print('Tensor atribites :: ',t1_tensor.type(), t1_tensor.dtype, t1_tensor.size(), '\n')


#matrix
t2 = [[1, 2, 3, 4],[4, 5, 6, 7],[7, 8, 9, 10]]
t2_tensor = torch.tensor(t2)
print('MAtrix ::',t2)
print('2D tensor ::',t2_tensor)
print('Tensor atribites :: ',t2_tensor.type(), t2_tensor.dtype, t2_tensor.size(), '\n')

#3D
t3 = [[[1., 2., 3.], [3., 4., 5.], [1., 2., 3.], [3., 4., 5.]],
          [[5., 6., 7.], [7., 8., 9.], [5., 6., 7.], [7., 8., 9.]]]
t3_tensor = torch.tensor(t3)
print('3D matrix ::',t3)
print('3D tensor ::',t3_tensor)
print('Tensor atribites :: ',t3_tensor.type(), t3_tensor.dtype, t3_tensor.size(), '\n')

Vector :: [1.0, 2.0, 3.0]
1D tensor :: tensor([1., 2., 3.])
Tensor atribites ::  torch.FloatTensor torch.float32 torch.Size([3]) 

MAtrix :: [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]]
2D tensor :: tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])
Tensor atribites ::  torch.LongTensor torch.int64 torch.Size([3, 4]) 

3D matrix :: [[[1.0, 2.0, 3.0], [3.0, 4.0, 5.0], [1.0, 2.0, 3.0], [3.0, 4.0, 5.0]], [[5.0, 6.0, 7.0], [7.0, 8.0, 9.0], [5.0, 6.0, 7.0], [7.0, 8.0, 9.0]]]
3D tensor :: tensor([[[1., 2., 3.],
         [3., 4., 5.],
         [1., 2., 3.],
         [3., 4., 5.]],

        [[5., 6., 7.],
         [7., 8., 9.],
         [5., 6., 7.],
         [7., 8., 9.]]])
Tensor atribites ::  torch.FloatTensor torch.float32 torch.Size([2, 4, 3]) 



In [29]:
# Getting components
print(t1_tensor[0])
print(t3_tensor[1])
# getting as scalar
print(t1_tensor[1].item())

print(t3_tensor[0][3])

tensor(1.)
tensor([[5., 6., 7.],
        [7., 8., 9.],
        [5., 6., 7.],
        [7., 8., 9.]])
2.0
tensor([3., 4., 5.])


In [30]:
# More ways to create tensors
x = torch.randn((3, 4, 5))
print(x, '\n')

n_arr = np.arange(0, -10, -2)
print(n_arr)
n_arr_tensor = torch.from_numpy(n_arr)
print('Tensor atribites :: ',n_arr_tensor.type(), n_arr_tensor.dtype, n_arr_tensor.size(), '\n')

tensor([[[-1.6211, -1.2314,  1.4720, -1.3922, -0.4772],
         [-1.5678,  0.0454, -1.4583, -1.2392,  0.1953],
         [ 1.9901,  1.0162,  2.1431,  1.0185,  0.5529],
         [ 0.9093, -0.5471,  1.2996, -0.2900,  0.6558]],

        [[-1.7943, -0.7773,  1.2733,  0.0298, -0.3415],
         [-0.4356,  0.5607,  0.2533, -0.3000,  0.0071],
         [ 1.7957,  0.1510,  0.5954, -1.4007,  0.4925],
         [-0.2614,  0.9615,  0.2604,  0.0302,  0.7600]],

        [[-0.1305, -0.0196,  0.8607, -0.0823, -0.0611],
         [ 1.8113, -0.1479,  0.7059,  0.5095, -0.9594],
         [ 0.2024,  0.8024, -1.6641, -1.6694, -0.9706],
         [-0.2952, -0.4026,  0.0812,  0.3668,  0.5682]]]) 

[ 0 -2 -4 -6 -8]
Tensor atribites ::  torch.IntTensor torch.int32 torch.Size([5]) 



In [31]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)
print(z_2.size())

# If the tensors are not compatible, torch will complain
torch.cat([x_1, x_2])

tensor([[-0.0960,  0.2966,  0.6056, -0.7538,  0.3556],
        [ 0.6688, -0.7586, -1.3654, -0.1393, -0.1203],
        [-0.1810, -0.7859,  0.8916, -0.7233, -1.0431],
        [-1.1571, -0.3016,  0.0730, -0.7563,  0.3740],
        [-0.1125, -1.1935, -1.9079,  1.1569, -1.4142]])
tensor([[-0.6979, -1.1499,  1.2982, -2.0633,  1.2955,  0.7786,  0.1135,  0.0259],
        [-1.2525,  0.1157,  1.6845, -0.8904, -1.3664, -0.9345,  0.9926,  1.1517]])
torch.Size([2, 8])


RuntimeError: Sizes of tensors must match except in dimension 0. Got 5 and 3 in dimension 1

In [32]:
# Reshaping
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))  # Reshape to 2 rows, 12 columns
# Same as above.  If one of the dimensions is -1, its size can be inferred
print(x.view(2, -1))

print(x.view(6, -1))

print(x.view(3, -1))

tensor([[[-0.0167, -0.8108, -0.9357,  0.3710],
         [ 1.5269, -0.2448, -2.6997,  1.9397],
         [ 0.1288, -0.5562, -0.2552,  1.2067]],

        [[-0.6697, -1.2896, -1.4762, -1.0845],
         [ 0.0307,  1.2059, -0.1073,  0.0818],
         [ 1.3897, -0.1534, -1.7852,  0.0083]]])
tensor([[-0.0167, -0.8108, -0.9357,  0.3710,  1.5269, -0.2448, -2.6997,  1.9397,
          0.1288, -0.5562, -0.2552,  1.2067],
        [-0.6697, -1.2896, -1.4762, -1.0845,  0.0307,  1.2059, -0.1073,  0.0818,
          1.3897, -0.1534, -1.7852,  0.0083]])
tensor([[-0.0167, -0.8108, -0.9357,  0.3710,  1.5269, -0.2448, -2.6997,  1.9397,
          0.1288, -0.5562, -0.2552,  1.2067],
        [-0.6697, -1.2896, -1.4762, -1.0845,  0.0307,  1.2059, -0.1073,  0.0818,
          1.3897, -0.1534, -1.7852,  0.0083]])
tensor([[-0.0167, -0.8108, -0.9357,  0.3710],
        [ 1.5269, -0.2448, -2.6997,  1.9397],
        [ 0.1288, -0.5562, -0.2552,  1.2067],
        [-0.6697, -1.2896, -1.4762, -1.0845],
        [ 0.0307,  1